### ISSUE TITLE
Truffle do not compile

### ISSUE THREAD

**Issue by ddbit** [SecurityTokenStandard/EIP-Spec#18]
It seems that package.json loads last openzeppelin@2.1 which now comes up with solidity 0.5 requirements while the rest of the code requires 0.4.*

```
truffle compile

```
```
SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;
```

**Comment by satyamakgec** [comment]
@ddbit could you please check your truffle or solidity version globally. Because according to the package.json truffle version and oz version are

       "openzeppelin-solidity": "^2.0.0"
       "truffle": "4.1.14"
I will changing a compile command. so it will always take the local truffle version not the global one

**Comment by satyamakgec** [comment]
now try to compile using `npm run compile`

**Comment by ddbit** [comment]
It doesn't work either because the caret ^ in
`"openzeppelin-solidity": "^2.0.0"` 
allows version 2.1.1 as the latest minor available.

I think you should either commit in repo your package-lock.json or to replace the caret with the tilde

`"openzeppelin-solidity": "~2.0.0"`

the second option works.

**Comment by satyamakgec** [comment]
We are supporting the `yarn.lock`. So use yarn install instead of `npm install`. It will definitely work

**Comment by ddbit** [comment]
Thanks for pointing that. However, as long as many people use npm my suggestion above still holds. Your choice. Cheers.
